import { ModelConfig } from './types';

// ============================================================
// All parameter keys, enum values, and defaults are sourced
// directly from the Replicate API model schemas via:
//   GET https://api.replicate.com/v1/models/{owner}/{name}
// ============================================================

// ============== VIDEO MODELS ==============

export const videoModels: ModelConfig[] = [
  // --- Google Veo ---
  {
    id: 'veo-3',
    replicateId: 'google/veo-3',
    name: 'Veo 3',
    provider: 'Google',
    providerColor: '#4285F4',
    description: 'Водещият модел на Google за генериране на видео с вграден звук. Създава кинематографични клипове с естествен аудио.',
    category: 'video',
    capabilities: ['text-to-video', 'image-to-video'],
    badge: 'Популярен',
    params: [
      {
        key: 'prompt',
        label: 'Промпт',
        type: 'textarea',
        required: true,
        placeholder: 'Опишете видеото, което искате да създадете...',
        description: 'Текстово описание на видеото. Включете детайли за композиция, камера и стил.',
      },
      {
        key: 'image',
        label: 'Начален кадър (опционално)',
        type: 'image',
        description: 'Качете изображение като начален кадър. Идеално 16:9 или 9:16, 1280x720.',
      },
      {
        key: 'duration',
        label: 'Продължителност (секунди)',
        type: 'select',
        sendAsNumber: true,
        options: [
          { value: '4', label: '4 секунди' },
          { value: '6', label: '6 секунди' },
          { value: '8', label: '8 секунди' },
        ],
        default: '8',
      },
      {
        key: 'aspect_ratio',
        label: 'Съотношение',
        type: 'select',
        options: [
          { value: '16:9', label: '16:9 (Пейзаж)' },
          { value: '9:16', label: '9:16 (Портрет)' },
        ],
        default: '16:9',
      },
      {
        key: 'resolution',
        label: 'Резолюция',
        type: 'select',
        options: [
          { value: '720p', label: '720p' },
          { value: '1080p', label: '1080p' },
        ],
        default: '1080p',
      },
      {
        key: 'generate_audio',
        label: 'Генериране на аудио',
        type: 'boolean',
        default: true,
        description: 'Включва автоматично генериране на синхронизирано аудио.',
      },
      {
        key: 'negative_prompt',
        label: 'Негативен промпт (опционално)',
        type: 'textarea',
        placeholder: 'Какво НЕ искате да се появява...',
        description: 'Описание на нежелани елементи във видеото.',
      },
    ],
  },
  {
    id: 'veo-3.1',
    replicateId: 'google/veo-3.1',
    name: 'Veo 3.1',
    provider: 'Google',
    providerColor: '#4285F4',
    description: 'Подобрена версия на Veo 3 с по-високо качество, контекстно аудио, референтни изображения и поддръжка на последен кадър.',
    category: 'video',
    capabilities: ['text-to-video', 'image-to-video'],
    badge: 'Ново',
    params: [
      {
        key: 'prompt',
        label: 'Промпт',
        type: 'textarea',
        required: true,
        placeholder: 'Опишете видеото, което искате да създадете...',
        description: 'Текстово описание на видеото.',
      },
      {
        key: 'image',
        label: 'Начален кадър (опционално)',
        type: 'image',
        description: 'Качете изображение като начален кадър за видеото.',
      },
      {
        key: 'last_frame',
        label: 'Краен кадър (опционално)',
        type: 'image',
        description: 'Качете изображение като краен кадър. Заедно с начален кадър, създава плавен преход.',
      },
      {
        key: 'reference_images',
        label: 'Референтни изображения (до 3)',
        type: 'images',
        maxImages: 3,
        description: 'Качете до 3 референтни изображения за стил и последователност.',
      },
      {
        key: 'duration',
        label: 'Продължителност (секунди)',
        type: 'select',
        sendAsNumber: true,
        options: [
          { value: '4', label: '4 секунди' },
          { value: '6', label: '6 секунди' },
          { value: '8', label: '8 секунди' },
        ],
        default: '8',
      },
      {
        key: 'aspect_ratio',
        label: 'Съотношение',
        type: 'select',
        options: [
          { value: '16:9', label: '16:9 (Пейзаж)' },
          { value: '9:16', label: '9:16 (Портрет)' },
        ],
        default: '16:9',
      },
      {
        key: 'resolution',
        label: 'Резолюция',
        type: 'select',
        options: [
          { value: '720p', label: '720p' },
          { value: '1080p', label: '1080p' },
        ],
        default: '1080p',
      },
      {
        key: 'generate_audio',
        label: 'Генериране на аудио',
        type: 'boolean',
        default: true,
        description: 'Включва автоматично генериране на синхронизирано аудио.',
      },
      {
        key: 'negative_prompt',
        label: 'Негативен промпт (опционално)',
        type: 'textarea',
        placeholder: 'Какво НЕ искате да се появява...',
      },
    ],
  },
  {
    id: 'veo-3-fast',
    replicateId: 'google/veo-3-fast',
    name: 'Veo 3 Fast',
    provider: 'Google',
    providerColor: '#4285F4',
    description: 'По-бърза и евтина версия на Veo 3. Генерира видео с вграден звук бързо и на ниска цена.',
    category: 'video',
    capabilities: ['text-to-video', 'image-to-video'],
    badge: 'Бързо',
    params: [
      {
        key: 'prompt',
        label: 'Промпт',
        type: 'textarea',
        required: true,
        placeholder: 'Опишете видеото, което искате да създадете...',
      },
      {
        key: 'image',
        label: 'Начален кадър (опционално)',
        type: 'image',
        description: 'Качете изображение като начален кадър.',
      },
      {
        key: 'duration',
        label: 'Продължителност (секунди)',
        type: 'select',
        sendAsNumber: true,
        options: [
          { value: '4', label: '4 секунди' },
          { value: '6', label: '6 секунди' },
          { value: '8', label: '8 секунди' },
        ],
        default: '8',
      },
      {
        key: 'aspect_ratio',
        label: 'Съотношение',
        type: 'select',
        options: [
          { value: '16:9', label: '16:9 (Пейзаж)' },
          { value: '9:16', label: '9:16 (Портрет)' },
        ],
        default: '16:9',
      },
      {
        key: 'resolution',
        label: 'Резолюция',
        type: 'select',
        options: [
          { value: '720p', label: '720p' },
          { value: '1080p', label: '1080p' },
        ],
        default: '1080p',
      },
      {
        key: 'generate_audio',
        label: 'Генериране на аудио',
        type: 'boolean',
        default: true,
      },
      {
        key: 'negative_prompt',
        label: 'Негативен промпт (опционално)',
        type: 'textarea',
        placeholder: 'Какво НЕ искате да се появява...',
      },
    ],
  },
  {
    id: 'veo-2',
    replicateId: 'google/veo-2',
    name: 'Veo 2',
    provider: 'Google',
    providerColor: '#4285F4',
    description: 'Модел за генериране на видео с реалистично движение и високо качество до 4K резолюция.',
    category: 'video',
    capabilities: ['text-to-video', 'image-to-video'],
    params: [
      {
        key: 'prompt',
        label: 'Промпт',
        type: 'textarea',
        required: true,
        placeholder: 'Опишете видеото, което искате да създадете...',
      },
      {
        key: 'image',
        label: 'Начален кадър (опционално)',
        type: 'image',
        description: 'Качете изображение като начален кадър.',
      },
      {
        key: 'duration',
        label: 'Продължителност (секунди)',
        type: 'select',
        sendAsNumber: true,
        options: [
          { value: '5', label: '5 секунди' },
          { value: '6', label: '6 секунди' },
          { value: '7', label: '7 секунди' },
          { value: '8', label: '8 секунди' },
        ],
        default: '5',
      },
      {
        key: 'aspect_ratio',
        label: 'Съотношение',
        type: 'select',
        options: [
          { value: '16:9', label: '16:9 (Пейзаж)' },
          { value: '9:16', label: '9:16 (Портрет)' },
        ],
        default: '16:9',
      },
    ],
  },
  {
    id: 'veo-3.1-fast',
    replicateId: 'google/veo-3.1-fast',
    name: 'Veo 3.1 Fast',
    provider: 'Google',
    providerColor: '#4285F4',
    description: 'Бърза версия на Veo 3.1 с високо качество, контекстно аудио и поддръжка на последен кадър.',
    category: 'video',
    capabilities: ['text-to-video', 'image-to-video'],
    badge: 'Ново & Бързо',
    params: [
      {
        key: 'prompt',
        label: 'Промпт',
        type: 'textarea',
        required: true,
        placeholder: 'Опишете видеото, което искате да създадете...',
      },
      {
        key: 'image',
        label: 'Начален кадър (опционално)',
        type: 'image',
        description: 'Качете изображение като начален кадър.',
      },
      {
        key: 'last_frame',
        label: 'Краен кадър (опционално)',
        type: 'image',
        description: 'Качете изображение като краен кадър за плавен преход.',
      },
      {
        key: 'duration',
        label: 'Продължителност (секунди)',
        type: 'select',
        sendAsNumber: true,
        options: [
          { value: '4', label: '4 секунди' },
          { value: '6', label: '6 секунди' },
          { value: '8', label: '8 секунди' },
        ],
        default: '8',
      },
      {
        key: 'aspect_ratio',
        label: 'Съотношение',
        type: 'select',
        options: [
          { value: '16:9', label: '16:9 (Пейзаж)' },
          { value: '9:16', label: '9:16 (Портрет)' },
        ],
        default: '16:9',
      },
      {
        key: 'resolution',
        label: 'Резолюция',
        type: 'select',
        options: [
          { value: '720p', label: '720p' },
          { value: '1080p', label: '1080p' },
        ],
        default: '1080p',
      },
      {
        key: 'generate_audio',
        label: 'Генериране на аудио',
        type: 'boolean',
        default: true,
      },
      {
        key: 'negative_prompt',
        label: 'Негативен промпт (опционално)',
        type: 'textarea',
        placeholder: 'Какво НЕ искате да се появява...',
      },
    ],
  },

  // --- OpenAI Sora ---
  {
    id: 'sora-2-pro',
    replicateId: 'openai/sora-2-pro',
    name: 'Sora 2 Pro',
    provider: 'OpenAI',
    providerColor: '#10a37f',
    description: 'Най-напредналият модел на OpenAI за генериране на видео със синхронизирано аудио. Кинематографично качество.',
    category: 'video',
    capabilities: ['text-to-video', 'image-to-video'],
    badge: 'Премиум',
    params: [
      {
        key: 'prompt',
        label: 'Промпт',
        type: 'textarea',
        required: true,
        placeholder: 'Опишете видеото, което искате да създадете...',
        description: 'Включете детайли за камера, осветление, стил и звук.',
      },
      {
        key: 'input_reference',
        label: 'Начално изображение (опционално)',
        type: 'image',
        description: 'Качете изображение като първи кадър на видеото.',
      },
      {
        key: 'seconds',
        label: 'Продължителност (секунди)',
        type: 'select',
        sendAsNumber: true,
        options: [
          { value: '4', label: '4 секунди' },
          { value: '8', label: '8 секунди' },
          { value: '12', label: '12 секунди' },
        ],
        default: '4',
      },
      {
        key: 'aspect_ratio',
        label: 'Съотношение',
        type: 'select',
        options: [
          { value: 'portrait', label: 'Портрет (720×1280)' },
          { value: 'landscape', label: 'Пейзаж (1280×720)' },
        ],
        default: 'landscape',
      },
      {
        key: 'resolution',
        label: 'Резолюция',
        type: 'select',
        options: [
          { value: 'standard', label: 'Стандартна (720p)' },
          { value: 'high', label: 'Висока (1024p)' },
        ],
        default: 'standard',
      },
    ],
  },
  {
    id: 'sora-2',
    replicateId: 'openai/sora-2',
    name: 'Sora 2',
    provider: 'OpenAI',
    providerColor: '#10a37f',
    description: 'Флагманският модел на OpenAI за видео генерация със синхронизирано аудио от текст или изображения.',
    category: 'video',
    capabilities: ['text-to-video', 'image-to-video'],
    params: [
      {
        key: 'prompt',
        label: 'Промпт',
        type: 'textarea',
        required: true,
        placeholder: 'Опишете видеото, което искате да създадете...',
      },
      {
        key: 'input_reference',
        label: 'Начално изображение (опционално)',
        type: 'image',
        description: 'Качете изображение като първи кадър на видеото.',
      },
      {
        key: 'seconds',
        label: 'Продължителност (секунди)',
        type: 'select',
        sendAsNumber: true,
        options: [
          { value: '4', label: '4 секунди' },
          { value: '8', label: '8 секунди' },
          { value: '12', label: '12 секунди' },
        ],
        default: '4',
      },
      {
        key: 'aspect_ratio',
        label: 'Съотношение',
        type: 'select',
        options: [
          { value: 'portrait', label: 'Портрет (720×1280)' },
          { value: 'landscape', label: 'Пейзаж (1280×720)' },
        ],
        default: 'landscape',
      },
    ],
  },

  // --- Kling ---
  {
    id: 'kling-v2.5-turbo-pro',
    replicateId: 'kwaivgi/kling-v2.5-turbo-pro',
    name: 'Kling v2.5 Turbo Pro',
    provider: 'Kuaishou',
    providerColor: '#FF6B35',
    description: 'Професионално ниво на text-to-video и image-to-video с плавно движение и кинематографична дълбочина.',
    category: 'video',
    capabilities: ['text-to-video', 'image-to-video'],
    badge: 'Топ избор',
    params: [
      {
        key: 'prompt',
        label: 'Промпт',
        type: 'textarea',
        required: true,
        placeholder: 'Опишете видеото, което искате да създадете...',
        description: 'Подробно описание на сцената, движението и стила.',
      },
      {
        key: 'start_image',
        label: 'Начално изображение (опционално)',
        type: 'image',
        description: 'Качете изображение за image-to-video анимация.',
      },
      {
        key: 'end_image',
        label: 'Краен кадър (опционално)',
        type: 'image',
        description: 'Качете изображение като последен кадър на видеото.',
      },
      {
        key: 'duration',
        label: 'Продължителност',
        type: 'select',
        sendAsNumber: true,
        options: [
          { value: '5', label: '5 секунди' },
          { value: '10', label: '10 секунди' },
        ],
        default: '5',
      },
      {
        key: 'aspect_ratio',
        label: 'Съотношение',
        type: 'select',
        options: [
          { value: '16:9', label: '16:9 (Пейзаж)' },
          { value: '9:16', label: '9:16 (Портрет)' },
          { value: '1:1', label: '1:1 (Квадрат)' },
        ],
        default: '16:9',
        description: 'Игнорира се ако е зададен начален кадър.',
      },
      {
        key: 'negative_prompt',
        label: 'Негативен промпт (опционално)',
        type: 'textarea',
        placeholder: 'Какво НЕ искате да се появява...',
      },
    ],
  },
  {
    id: 'kling-v2.1',
    replicateId: 'kwaivgi/kling-v2.1',
    name: 'Kling v2.1',
    provider: 'Kuaishou',
    providerColor: '#FF6B35',
    description: 'Генериране на 5 и 10 секундни видеа в 720p и 1080p от начално изображение.',
    category: 'video',
    capabilities: ['image-to-video'],
    params: [
      {
        key: 'prompt',
        label: 'Промпт',
        type: 'textarea',
        required: true,
        placeholder: 'Опишете видеото, което искате да създадете...',
      },
      {
        key: 'start_image',
        label: 'Начално изображение',
        type: 'image',
        required: true,
        description: 'Качете начално изображение за видеото. Задължително за този модел.',
      },
      {
        key: 'end_image',
        label: 'Краен кадър (опционално, само Pro)',
        type: 'image',
        description: 'Качете изображение като краен кадър (само в Pro режим).',
      },
      {
        key: 'duration',
        label: 'Продължителност',
        type: 'select',
        sendAsNumber: true,
        options: [
          { value: '5', label: '5 секунди' },
          { value: '10', label: '10 секунди' },
        ],
        default: '5',
      },
      {
        key: 'mode',
        label: 'Режим',
        type: 'select',
        options: [
          { value: 'standard', label: 'Стандартен (720p)' },
          { value: 'pro', label: 'Професионален (1080p)' },
        ],
        default: 'standard',
      },
      {
        key: 'negative_prompt',
        label: 'Негативен промпт (опционално)',
        type: 'textarea',
        placeholder: 'Какво НЕ искате да се появява...',
      },
    ],
  },
];

// ============== IMAGE MODELS ==============

export const imageModels: ModelConfig[] = [
  // --- Google Imagen ---
  {
    id: 'imagen-4',
    replicateId: 'google/imagen-4',
    name: 'Imagen 4',
    provider: 'Google',
    providerColor: '#4285F4',
    description: 'Флагманският модел на Google за генериране на изображения. Фини детайли, разнообразни стилове и гъвкава резолюция.',
    category: 'image',
    capabilities: ['text-to-image'],
    badge: 'Популярен',
    params: [
      {
        key: 'prompt',
        label: 'Промпт',
        type: 'textarea',
        required: true,
        placeholder: 'Опишете изображението, което искате да създадете...',
        description: 'Детайлно описание на желаното изображение.',
      },
      {
        key: 'aspect_ratio',
        label: 'Съотношение',
        type: 'select',
        options: [
          { value: '1:1', label: '1:1 (Квадрат)' },
          { value: '16:9', label: '16:9 (Пейзаж)' },
          { value: '9:16', label: '9:16 (Портрет)' },
          { value: '4:3', label: '4:3' },
          { value: '3:4', label: '3:4' },
        ],
        default: '1:1',
      },
      {
        key: 'safety_filter_level',
        label: 'Филтър за безопасност',
        type: 'select',
        options: [
          { value: 'block_low_and_above', label: 'Строг' },
          { value: 'block_medium_and_above', label: 'Среден' },
          { value: 'block_only_high', label: 'Минимален' },
        ],
        default: 'block_only_high',
      },
      {
        key: 'output_format',
        label: 'Формат',
        type: 'select',
        options: [
          { value: 'jpg', label: 'JPG' },
          { value: 'png', label: 'PNG' },
        ],
        default: 'jpg',
      },
    ],
  },
  {
    id: 'imagen-4-ultra',
    replicateId: 'google/imagen-4-ultra',
    name: 'Imagen 4 Ultra',
    provider: 'Google',
    providerColor: '#4285F4',
    description: 'Ултра версия на Imagen 4 — когато качеството е по-важно от скоростта и цената.',
    category: 'image',
    capabilities: ['text-to-image'],
    badge: 'Премиум',
    params: [
      {
        key: 'prompt',
        label: 'Промпт',
        type: 'textarea',
        required: true,
        placeholder: 'Опишете изображението, което искате да създадете...',
      },
      {
        key: 'aspect_ratio',
        label: 'Съотношение',
        type: 'select',
        options: [
          { value: '1:1', label: '1:1 (Квадрат)' },
          { value: '16:9', label: '16:9 (Пейзаж)' },
          { value: '9:16', label: '9:16 (Портрет)' },
          { value: '4:3', label: '4:3' },
          { value: '3:4', label: '3:4' },
        ],
        default: '1:1',
      },
      {
        key: 'safety_filter_level',
        label: 'Филтър за безопасност',
        type: 'select',
        options: [
          { value: 'block_low_and_above', label: 'Строг' },
          { value: 'block_medium_and_above', label: 'Среден' },
          { value: 'block_only_high', label: 'Минимален' },
        ],
        default: 'block_only_high',
      },
    ],
  },
  {
    id: 'imagen-4-fast',
    replicateId: 'google/imagen-4-fast',
    name: 'Imagen 4 Fast',
    provider: 'Google',
    providerColor: '#4285F4',
    description: 'Бърза версия на Imagen 4 — когато скоростта и цената са по-важни от качеството.',
    category: 'image',
    capabilities: ['text-to-image'],
    badge: 'Бързо',
    params: [
      {
        key: 'prompt',
        label: 'Промпт',
        type: 'textarea',
        required: true,
        placeholder: 'Опишете изображението, което искате да създадете...',
      },
      {
        key: 'aspect_ratio',
        label: 'Съотношение',
        type: 'select',
        options: [
          { value: '1:1', label: '1:1 (Квадрат)' },
          { value: '16:9', label: '16:9 (Пейзаж)' },
          { value: '9:16', label: '9:16 (Портрет)' },
          { value: '4:3', label: '4:3' },
          { value: '3:4', label: '3:4' },
        ],
        default: '1:1',
      },
      {
        key: 'safety_filter_level',
        label: 'Филтър за безопасност',
        type: 'select',
        options: [
          { value: 'block_low_and_above', label: 'Строг' },
          { value: 'block_medium_and_above', label: 'Среден' },
          { value: 'block_only_high', label: 'Минимален' },
        ],
        default: 'block_only_high',
      },
    ],
  },
  {
    id: 'imagen-3',
    replicateId: 'google/imagen-3',
    name: 'Imagen 3',
    provider: 'Google',
    providerColor: '#4285F4',
    description: 'Модел на Google за висококачествено генериране на изображения с подобрени детайли, осветление и красота.',
    category: 'image',
    capabilities: ['text-to-image'],
    params: [
      {
        key: 'prompt',
        label: 'Промпт',
        type: 'textarea',
        required: true,
        placeholder: 'Опишете изображението, което искате да създадете...',
      },
      {
        key: 'aspect_ratio',
        label: 'Съотношение',
        type: 'select',
        options: [
          { value: '1:1', label: '1:1 (Квадрат)' },
          { value: '16:9', label: '16:9 (Пейзаж)' },
          { value: '9:16', label: '9:16 (Портрет)' },
          { value: '4:3', label: '4:3' },
          { value: '3:4', label: '3:4' },
        ],
        default: '1:1',
      },
    ],
  },
  {
    id: 'imagen-3-fast',
    replicateId: 'google/imagen-3-fast',
    name: 'Imagen 3 Fast',
    provider: 'Google',
    providerColor: '#4285F4',
    description: 'Бърз и евтин модел Imagen 3 — когато цената или скоростта са по-важни от качеството.',
    category: 'image',
    capabilities: ['text-to-image'],
    badge: 'Бързо',
    params: [
      {
        key: 'prompt',
        label: 'Промпт',
        type: 'textarea',
        required: true,
        placeholder: 'Опишете изображението, което искате да създадете...',
      },
      {
        key: 'aspect_ratio',
        label: 'Съотношение',
        type: 'select',
        options: [
          { value: '1:1', label: '1:1 (Квадрат)' },
          { value: '16:9', label: '16:9 (Пейзаж)' },
          { value: '9:16', label: '9:16 (Портрет)' },
          { value: '4:3', label: '4:3' },
          { value: '3:4', label: '3:4' },
        ],
        default: '1:1',
      },
    ],
  },

  // --- Google Nano Banana (Gemini image) ---
  {
    id: 'nano-banana-pro',
    replicateId: 'google/nano-banana-pro',
    name: 'Nano Banana Pro',
    provider: 'Google',
    providerColor: '#4285F4',
    description: 'Най-добрият модел на Google за генериране и редактиране на изображения. Поддържа до 14 входни изображения и до 4K.',
    category: 'image',
    capabilities: ['text-to-image', 'image-editing'],
    badge: 'Редактиране',
    params: [
      {
        key: 'prompt',
        label: 'Промпт',
        type: 'textarea',
        required: true,
        placeholder: 'Опишете какво искате да създадете или как да редактирате изображението...',
        description: 'За редактиране, опишете промените, които искате.',
      },
      {
        key: 'image_input',
        label: 'Входни изображения (опционално)',
        type: 'images',
        maxImages: 14,
        description: 'Качете изображения за трансформиране или референция (до 14).',
      },
      {
        key: 'aspect_ratio',
        label: 'Съотношение',
        type: 'select',
        options: [
          { value: 'match_input_image', label: 'Като входното' },
          { value: '1:1', label: '1:1 (Квадрат)' },
          { value: '16:9', label: '16:9 (Пейзаж)' },
          { value: '9:16', label: '9:16 (Портрет)' },
          { value: '4:3', label: '4:3' },
          { value: '3:4', label: '3:4' },
          { value: '3:2', label: '3:2' },
          { value: '2:3', label: '2:3' },
          { value: '4:5', label: '4:5' },
          { value: '5:4', label: '5:4' },
          { value: '21:9', label: '21:9 (Ултра широк)' },
        ],
        default: 'match_input_image',
      },
      {
        key: 'resolution',
        label: 'Резолюция',
        type: 'select',
        options: [
          { value: '1K', label: '1K' },
          { value: '2K', label: '2K' },
          { value: '4K', label: '4K' },
        ],
        default: '2K',
      },
    ],
  },
  {
    id: 'nano-banana',
    replicateId: 'google/nano-banana',
    name: 'Nano Banana',
    provider: 'Google',
    providerColor: '#4285F4',
    description: 'Модел за генериране и редактиране на изображения в Gemini 2.5. Бърз, разговорен и мултимодален.',
    category: 'image',
    capabilities: ['text-to-image', 'image-editing'],
    badge: 'Редактиране',
    params: [
      {
        key: 'prompt',
        label: 'Промпт',
        type: 'textarea',
        required: true,
        placeholder: 'Опишете какво искате да създадете или как да редактирате изображението...',
        description: 'Опишете промените на естествен език.',
      },
      {
        key: 'image_input',
        label: 'Входни изображения (опционално)',
        type: 'images',
        maxImages: 3,
        description: 'Качете изображения за редактиране или референция.',
      },
      {
        key: 'aspect_ratio',
        label: 'Съотношение',
        type: 'select',
        options: [
          { value: 'match_input_image', label: 'Като входното' },
          { value: '1:1', label: '1:1 (Квадрат)' },
          { value: '16:9', label: '16:9 (Пейзаж)' },
          { value: '9:16', label: '9:16 (Портрет)' },
          { value: '4:3', label: '4:3' },
          { value: '3:4', label: '3:4' },
          { value: '3:2', label: '3:2' },
          { value: '2:3', label: '2:3' },
          { value: '4:5', label: '4:5' },
          { value: '5:4', label: '5:4' },
          { value: '21:9', label: '21:9 (Ултра широк)' },
        ],
        default: 'match_input_image',
      },
    ],
  },

  // --- OpenAI ---
  {
    id: 'gpt-image-1.5',
    replicateId: 'openai/gpt-image-1.5',
    name: 'GPT Image 1.5',
    provider: 'OpenAI',
    providerColor: '#10a37f',
    description: 'Най-новият модел на OpenAI за генериране и редактиране на изображения с прецизен контрол и следване на инструкции.',
    category: 'image',
    capabilities: ['text-to-image', 'image-editing'],
    badge: 'Ново',
    params: [
      {
        key: 'prompt',
        label: 'Промпт',
        type: 'textarea',
        required: true,
        placeholder: 'Опишете изображението или промените, които искате...',
        description: 'Бъдете конкретни — включете детайли за осветление, стил, текстура.',
      },
      {
        key: 'input_images',
        label: 'Изображения за редактиране (опционално)',
        type: 'images',
        maxImages: 5,
        description: 'Качете изображения за редактиране. Без тях се генерира ново.',
      },
      {
        key: 'quality',
        label: 'Качество',
        type: 'select',
        options: [
          { value: 'auto', label: 'Автоматично' },
          { value: 'high', label: 'Високо' },
          { value: 'medium', label: 'Средно' },
          { value: 'low', label: 'Ниско' },
        ],
        default: 'auto',
      },
      {
        key: 'aspect_ratio',
        label: 'Съотношение',
        type: 'select',
        options: [
          { value: '1:1', label: '1:1 (Квадрат)' },
          { value: '3:2', label: '3:2 (Пейзаж)' },
          { value: '2:3', label: '2:3 (Портрет)' },
        ],
        default: '1:1',
      },
      {
        key: 'background',
        label: 'Фон',
        type: 'select',
        options: [
          { value: 'auto', label: 'Автоматично' },
          { value: 'transparent', label: 'Прозрачен' },
          { value: 'opaque', label: 'Плътен' },
        ],
        default: 'auto',
      },
      {
        key: 'output_format',
        label: 'Формат',
        type: 'select',
        options: [
          { value: 'webp', label: 'WebP' },
          { value: 'png', label: 'PNG' },
          { value: 'jpeg', label: 'JPEG' },
        ],
        default: 'webp',
      },
    ],
  },

  // --- Ideogram ---
  {
    id: 'ideogram-character',
    replicateId: 'ideogram-ai/ideogram-character',
    name: 'Ideogram Character',
    provider: 'Ideogram',
    providerColor: '#E040FB',
    description: 'Генериране на последователни персонажи от едно референтно изображение. Поддържа различни стилове и инпейнтинг.',
    category: 'image',
    capabilities: ['character-consistency', 'image-editing'],
    badge: 'Персонажи',
    params: [
      {
        key: 'prompt',
        label: 'Промпт',
        type: 'textarea',
        required: true,
        placeholder: 'Опишете сцената с вашия персонаж...',
        description: 'Опишете как искате да изглежда персонажът в новата сцена.',
      },
      {
        key: 'character_reference_image',
        label: 'Референтно изображение на персонаж',
        type: 'image',
        required: true,
        description: 'Качете ясна снимка на персонажа, който искате да запазите.',
      },
      {
        key: 'aspect_ratio',
        label: 'Съотношение',
        type: 'select',
        options: [
          { value: '1:1', label: '1:1 (Квадрат)' },
          { value: '16:9', label: '16:9 (Пейзаж)' },
          { value: '9:16', label: '9:16 (Портрет)' },
          { value: '4:3', label: '4:3' },
          { value: '3:4', label: '3:4' },
          { value: '3:2', label: '3:2' },
          { value: '2:3', label: '2:3' },
          { value: '4:5', label: '4:5' },
          { value: '5:4', label: '5:4' },
        ],
        default: '1:1',
      },
      {
        key: 'style_type',
        label: 'Стил',
        type: 'select',
        options: [
          { value: 'Auto', label: 'Автоматичен' },
          { value: 'Realistic', label: 'Реалистичен' },
          { value: 'Fiction', label: 'Фикция' },
        ],
        default: 'Auto',
      },
      {
        key: 'rendering_speed',
        label: 'Скорост на рендериране',
        type: 'select',
        options: [
          { value: 'Default', label: 'По подразбиране' },
          { value: 'Turbo', label: 'Турбо' },
          { value: 'Quality', label: 'Качество' },
        ],
        default: 'Default',
      },
    ],
  },
  {
    id: 'ideogram-v3-quality',
    replicateId: 'ideogram-ai/ideogram-v3-quality',
    name: 'Ideogram v3 Quality',
    provider: 'Ideogram',
    providerColor: '#E040FB',
    description: 'Най-високото качество на Ideogram v3. Зашеметяващ реализъм, креативни дизайни и последователни стилове.',
    category: 'image',
    capabilities: ['text-to-image'],
    badge: 'Премиум',
    params: [
      {
        key: 'prompt',
        label: 'Промпт',
        type: 'textarea',
        required: true,
        placeholder: 'Опишете изображението, което искате да създадете...',
        description: 'Прецизно описание за най-добри резултати.',
      },
      {
        key: 'aspect_ratio',
        label: 'Съотношение',
        type: 'select',
        options: [
          { value: '1:1', label: '1:1 (Квадрат)' },
          { value: '16:9', label: '16:9 (Пейзаж)' },
          { value: '9:16', label: '9:16 (Портрет)' },
          { value: '4:3', label: '4:3' },
          { value: '3:4', label: '3:4' },
          { value: '3:2', label: '3:2' },
          { value: '2:3', label: '2:3' },
          { value: '4:5', label: '4:5' },
          { value: '5:4', label: '5:4' },
        ],
        default: '1:1',
      },
      {
        key: 'style_type',
        label: 'Тип стил',
        type: 'select',
        options: [
          { value: 'None', label: 'Без' },
          { value: 'Auto', label: 'Автоматичен' },
          { value: 'General', label: 'Общ' },
          { value: 'Realistic', label: 'Реалистичен' },
          { value: 'Design', label: 'Дизайн' },
        ],
        default: 'None',
      },
      {
        key: 'magic_prompt_option',
        label: 'Магически промпт',
        type: 'select',
        options: [
          { value: 'Auto', label: 'Автоматично' },
          { value: 'On', label: 'Включен' },
          { value: 'Off', label: 'Изключен' },
        ],
        default: 'Auto',
        description: 'Автоматично подобряване на промпта от Ideogram.',
      },
      {
        key: 'style_reference_images',
        label: 'Референция за стил (опционално)',
        type: 'images',
        maxImages: 3,
        description: 'Качете изображения като референция за стил.',
      },
    ],
  },
  {
    id: 'ideogram-v3-turbo',
    replicateId: 'ideogram-ai/ideogram-v3-turbo',
    name: 'Ideogram v3 Turbo',
    provider: 'Ideogram',
    providerColor: '#E040FB',
    description: 'Най-бързият и евтин Ideogram v3. Зашеметяващ реализъм с максимална скорост.',
    category: 'image',
    capabilities: ['text-to-image'],
    badge: 'Бързо',
    params: [
      {
        key: 'prompt',
        label: 'Промпт',
        type: 'textarea',
        required: true,
        placeholder: 'Опишете изображението, което искате да създадете...',
      },
      {
        key: 'aspect_ratio',
        label: 'Съотношение',
        type: 'select',
        options: [
          { value: '1:1', label: '1:1 (Квадрат)' },
          { value: '16:9', label: '16:9 (Пейзаж)' },
          { value: '9:16', label: '9:16 (Портрет)' },
          { value: '4:3', label: '4:3' },
          { value: '3:4', label: '3:4' },
          { value: '3:2', label: '3:2' },
          { value: '2:3', label: '2:3' },
          { value: '4:5', label: '4:5' },
          { value: '5:4', label: '5:4' },
        ],
        default: '1:1',
      },
      {
        key: 'style_type',
        label: 'Тип стил',
        type: 'select',
        options: [
          { value: 'None', label: 'Без' },
          { value: 'Auto', label: 'Автоматичен' },
          { value: 'General', label: 'Общ' },
          { value: 'Realistic', label: 'Реалистичен' },
          { value: 'Design', label: 'Дизайн' },
        ],
        default: 'None',
      },
      {
        key: 'magic_prompt_option',
        label: 'Магически промпт',
        type: 'select',
        options: [
          { value: 'Auto', label: 'Автоматично' },
          { value: 'On', label: 'Включен' },
          { value: 'Off', label: 'Изключен' },
        ],
        default: 'Auto',
      },
      {
        key: 'style_reference_images',
        label: 'Референция за стил (опционално)',
        type: 'images',
        maxImages: 3,
        description: 'Качете изображения като референция за стил.',
      },
    ],
  },
  {
    id: 'ideogram-v3-balanced',
    replicateId: 'ideogram-ai/ideogram-v3-balanced',
    name: 'Ideogram v3 Balanced',
    provider: 'Ideogram',
    providerColor: '#E040FB',
    description: 'Балансиран модел между скорост, качество и цена. Реализъм и креативни дизайни.',
    category: 'image',
    capabilities: ['text-to-image'],
    params: [
      {
        key: 'prompt',
        label: 'Промпт',
        type: 'textarea',
        required: true,
        placeholder: 'Опишете изображението, което искате да създадете...',
      },
      {
        key: 'aspect_ratio',
        label: 'Съотношение',
        type: 'select',
        options: [
          { value: '1:1', label: '1:1 (Квадрат)' },
          { value: '16:9', label: '16:9 (Пейзаж)' },
          { value: '9:16', label: '9:16 (Портрет)' },
          { value: '4:3', label: '4:3' },
          { value: '3:4', label: '3:4' },
          { value: '3:2', label: '3:2' },
          { value: '2:3', label: '2:3' },
          { value: '4:5', label: '4:5' },
          { value: '5:4', label: '5:4' },
        ],
        default: '1:1',
      },
      {
        key: 'style_type',
        label: 'Тип стил',
        type: 'select',
        options: [
          { value: 'None', label: 'Без' },
          { value: 'Auto', label: 'Автоматичен' },
          { value: 'General', label: 'Общ' },
          { value: 'Realistic', label: 'Реалистичен' },
          { value: 'Design', label: 'Дизайн' },
        ],
        default: 'None',
      },
      {
        key: 'magic_prompt_option',
        label: 'Магически промпт',
        type: 'select',
        options: [
          { value: 'Auto', label: 'Автоматично' },
          { value: 'On', label: 'Включен' },
          { value: 'Off', label: 'Изключен' },
        ],
        default: 'Auto',
      },
      {
        key: 'style_reference_images',
        label: 'Референция за стил (опционално)',
        type: 'images',
        maxImages: 3,
        description: 'Качете изображения като референция за стил.',
      },
    ],
  },
];

export const allModels = [...videoModels, ...imageModels];

export function getModelById(id: string): ModelConfig | undefined {
  return allModels.find((m) => m.id === id);
}
